# _config.yml

# サイトの基本設定（SEO的にも軽く反映される）
title: Minimal Peil
description: ペイルの暮らしの記録と学びのノート
baseurl: "" # カスタムドメインだから空でOK
url: "https://www.minimal-peil.com"

# Markdownの変換エンジン指定
markdown: kramdown

theme: minima
future: true

# Google AnalyticsのトラッキングID（使うならここに入れてもOK）
# google_analytics: G-89D1F7DMB6

# その他（必要なら追記できる）
